-- 13.Find the total revenue generated by each customer and display the top 3 customers who spent the most. 
-- including their first name, last name, and total revenue spent.

select c.customer_id, first_name, c.last_name, sum(s.quantity) as Total_books_purchased, sum(s.total_amount) as Total_revenue_generated
from sales s
inner join customers c on s.customer_id = c.customer_id
group by c.customer_id
order by Total_revenue_generated desc
limit 3;